version: '3.9'
services:
  mongo:
    container_name: mv-db-mongo
    image: mongo
    volumes:
      - ./docker_volumes/mongo/config/mongod.conf:/etc/mongod.conf
      - mv-db-mongo-volume:/data/db
      - ./docker_volumes/mongo/scripts/rs-init.sh:/scripts/rs-init.sh
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    entrypoint: ['/usr/bin/mongod', '--config', '/etc/mongod.conf']
    networks:
      - mv-docker-network
  # mongo-express:
  #   container_name: mv-mongo-express
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   networks:
  #     - mv-docker-network
  #   environment:
  #     # ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     # ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mv-db-mongo://mongo:27017/
networks:
  mv-docker-network:
    name: mv-docker-network
volumes:
  mv-db-mongo-volume: